name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
      - feat/insiders-setup # temporary for testing action

# Setup from https://squidfunk.github.io/mkdocs-material/publishing-your-site/#with-github-actions
jobs:
  deploy:
    name: Deploy documentation
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install MkDocs Material Insiders
        run: pip install git+https://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@github.com/squidfunk/mkdocs-material-insiders.git
      - name: Deploy docs
        run: mkdocs gh-deploy --force
env:
  INSIDERS_GITHUB_TOKEN: ${{ secrets.INSIDERS_GITHUB_TOKEN }}
